"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 1000000

# My prompt
format = """
$directory$git_branch$git_status$fill$package$cmd_duration$package
$character
"""


palette = "catppuccin_mocha"


[directory]
read_only = "󰌾"
style = "bold fg:text bg:base"
format = '[](bold base)[$path ]($style)[$read_only]($read_only_style)'
truncation_length = 3
truncation_symbol = "…/"
read_only_style = 'bold fg:red bg:mantle'

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
format='[](bold base)[$symbol$branch(:$remote_branch)](bold bg:base fg:text)[](bold base)'
style='bold bright fg:white bg:base'
symbol=""

[git_status]
ignore_submodules = true
untracked = ""
style = "bg:color_aqua"
ahead = '⇡${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[cmd_duration]
min_time = 2000
format = '[[ 󰔟$duration ](fg:color_fg0)]($style)'

[package]
disabled=false

[character]
success_symbol = '[➜](bold fg:green bg:base)[](bold base)'
error_symbol = '[✖](bold fg:red bg:base)[](bold base)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

